-- SQL Database for Office Appliances Stock (ATK) - Initializer Script

-- 1. Table: pegawai
CREATE TABLE pegawai (
    id_pegawai INTEGER PRIMARY KEY,
    nama_pegawai TEXT NOT NULL UNIQUE
);

-- 2. Table: barang_atk (Master List)
-- Catatan: UNIQUE constraint pada nama_barang TIDAK DIGUNAKAN di sini
-- agar bisa menampung 321 entri penuh dari Book1, meskipun beberapa nama barang duplikat/mirip.
CREATE TABLE barang_atk (
    id_barang INTEGER PRIMARY KEY,
    kode_barang TEXT,
    nama_barang_sakti TEXT,
    nama_barang TEXT NOT NULL,
    kategori TEXT,
    satuan TEXT NOT NULL
);

-- 3. Table: stock (Current Quantity)
-- PRIMARY KEY adalah id_barang (one-to-one relationship with barang_atk)
CREATE TABLE stock (
    id_barang INTEGER PRIMARY KEY,
    jumlah_tersedia INTEGER NOT NULL,
    FOREIGN KEY (id_barang) REFERENCES barang_atk(id_barang)
);

-- 4. Table: pengeluaran (Transaction Header)
CREATE TABLE pengeluaran (
    id INTEGER PRIMARY KEY,
    no_bukti_full TEXT NOT NULL UNIQUE,
    tanggal_pengeluaran DATE NOT NULL,
    pegawai_id INTEGER NOT NULL,
    FOREIGN KEY (pegawai_id) REFERENCES pegawai(id_pegawai)
);

-- 5. Table: detail_pengeluaran (Transaction Lines)
CREATE TABLE detail_pengeluaran (
    id INTEGER PRIMARY KEY,
    pengeluaran_id INTEGER NOT NULL,
    barang_atk_id INTEGER NOT NULL,
    jumlah_keluar INTEGER NOT NULL,
    FOREIGN KEY (pengeluaran_id) REFERENCES pengeluaran(id),
    FOREIGN KEY (barang_atk_id) REFERENCES barang_atk(id_barang)
);

------------------------------------------------------
-- INSERT statements for pegawai (39 entries)
------------------------------------------------------
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (1, 'Ir. Royke Oct Rawung');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (2, 'Marthedy Mormin Tenggehi');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (3, 'Tonny Herman Johan Mangempis');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (4, 'Anis Karimah');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (5, 'Daniel Salu');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (6, 'Defi Astuti Anggraeni');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (7, 'Deyvi Stella Rumangkang');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (8, 'Elrini Wuisan');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (9, 'Enggelin Giacinta Wongkar');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (10, 'Fadila Ahmad');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (11, 'Farhan');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (12, 'Frisca Ully Saragih');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (13, 'Gaberiel');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (14, 'Habel Nitalessy');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (15, 'Ira Yuliana Posumah');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (16, 'Julianti Hartanto');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (17, 'Kennedy Umadji');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (18, 'Lazia Outenty Bimbangnaung');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (19, 'Maskhur Solikhudin');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (20, 'Munawir Kobis');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (21, 'Natalia Ondang');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (22, 'Ni Putu Beliana Puspita Sari');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (23, 'Nik''mah');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (24, 'Olivia Widyawaty Sahambangung');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (25, 'Rahadita Nur Haida');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (26, 'Ricky Sethaan');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (27, 'Rikky Rugian');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (28, 'Roy Samalukang');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (29, 'Sastadeferah Risab');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (30, 'Vini Cristin');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (31, 'Vivi Novita Sumampouw');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (32, 'Vonny Joice Lalujan');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (33, 'Wardzatul Khoiriyah');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (34, 'Weny Fitrah Anwari');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (35, 'Yanti Jane Ivonne Kaeng');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (36, 'Arista Roza Belawan SST');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (37, 'Santi H Putri');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (38, 'Mia Wahyumiranti, SM');
INSERT INTO pegawai (id_pegawai, nama_pegawai) VALUES (39, 'Lusiana Tungkagi');

------------------------------------------------------
-- INSERT statements for barang_atk (321 entries)
------------------------------------------------------
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (1, '1010301001000001', 'BALLPOINT', 'PULPEN STANDARD AE7 ZYRCON BALL', 'ALAT TULIS', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (2, '1010301001000016', 'PENSIL 2B', 'PENSIL 2B KENKO', 'ALAT TULIS', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (3, '1010301001000030', 'Pulpen Standard Boldliner', 'PULPEN STANDARD BOLDLINER PRO 0.8', 'ALAT TULIS', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (4, '1010301001000157', 'ZEBRA HANNA PEN', 'PULPEN ZEBRA HANA 4C', 'ALAT TULIS', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (5, '1010301003000004', 'PAPER CLIPS NO. 3', 'TRIGONAL PAPER CLIPS KENKO NO.3', 'PENJEPIT KERTAS', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (6, '1010301003000004', 'PAPER CLIPS NO. 3', 'TRIGONAL PAPER CLIPS ZRM NO.3', 'PENJEPIT KERTAS', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (7, '1010301003000013', 'Binder Clip 200 Dos', 'BINDER CLIPS KENKO NO.200', 'PENJEPIT KERTAS', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (8, '1010301003000014', 'Binder Clip 260 Dos', 'BINDER CLIPS KENKO NO.260', 'PENJEPIT KERTAS', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (9, '1010301003000045', 'BINDERCLIPS NO 107', 'BINDER CLIPS KENKO NO.107', 'PENJEPIT KERTAS', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (10, '1010301003000058', 'Binder Clips ZRM No.111', 'BINDER CLIPS KENKO NO.111', 'PENJEPIT KERTAS', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (11, '1010301004000028', 'Penghapus Staedtler Rasoplast Putih', 'PENGHAPUS PENSIL STAEDTLER RASOPLAST', 'PENGHAPUS', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (12, '1010301006000014', 'Map BPS A4', 'MAP BPS ST2023', 'ORDNER & MAP', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (13, '1010301006000016', 'Map Tali Plastik', 'MAP TALI PLASTIK', 'ORDNER & MAP', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (14, '1010301006000097', 'ODNER FILE 7CM', 'ORDNER 70 MM', 'ORDNER & MAP', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (15, '1010301007000005', 'Penggaris Kenko Besi 60cm', 'PENGGARIS KENKO BESI 50 CM', 'PENGGARIS', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (16, '1010301008000001', 'Cutter', 'CUTTER OFFICEPLUS', 'CUTTER', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (17, '1010301008000002 / 1010301008000015', 'Isi Cutter / Isi Silet Kenko L-150', 'ISI CUTTER JOYKO L-150', 'CUTTER', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (18, '1010301008000013', 'Rautan ZRM Kecil', 'RAUTAN KECIL WARNA ZRM', 'RAUTAN', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (19, '1010301010000009', 'Double Tape', 'DOUBLE TIP OFFICEPLUS', 'ALAT PEREKAT', 'ROL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (20, '1010301010000014', 'Lakban Hitam', 'LAKBAN BESAR HITAM', 'ALAT PEREKAT', 'ROL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (21, '1010301010000015 / 1010301010000031', 'Lakban Daimaru / Selotip Goldfox Besar Bening', 'LAKBAN BESAR BENING', 'ALAT PEREKAT', 'ROL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (22, '1010301012000013', 'Stapler HD-10', 'STAPLER HD-10 GREEBEL', 'STAPLER', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (23, '1010301013000018', 'STAPLER HD-45', 'ISI STAPLES JOYKO NO.10', 'ISI STAPLES', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (24, '1010301013000021', 'ISI STAPLES NO.3', 'ISI STAPLES ZRM NO.3', 'ISI STAPLES', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (25, '1010301014000042', 'Leaflet ST2023', 'LEAFLET ST2023', 'BARANG ST23', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (26, '1010301999000001', 'Gunting Besar', 'GUNTING ZRM', 'ATK LAINNYA', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (27, '1010301999000035', 'Pronto Mark N Notes', 'PAGE MARKER PRONTO 5 COLOURS', 'ATK LAINNYA', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (28, '1010301999000061', 'POST IT 3M JOYKO', 'POST-IT STICKY NOTES', 'ATK LAINNYA', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (29, '1010302001000019', 'KERTAS HVS A4', 'KERTAS HVS A4', 'KERTAS HVS', 'RIM');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (30, '1010302001000023', 'KERTAS HVS F4', 'KERTAS HVS F4', 'KERTAS HVS', 'RIM');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (31, '1010304004000077', 'Cartridge Original HP CF289A', 'CARTRIDGE TONER CF289A HP', 'TINTA/TONER PRINTER', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (32, '1010304004000078', 'Tinta Epson 774 L1455 Original Hitam', 'TINTA EPSON 774 BLACK', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (33, '1010304004000099', 'TINTA EPSON L1110 MAGENTA 21', 'TINTA EPSON 003 MAGENTA', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (34, '1010304004000104', 'Tinta Epson 003 L1110 Original Cyan', 'TINTA EPSON 003 CYAN', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (35, '1010304004000105', 'Tinta Epson 003 L1110 Original Yellow', 'TINTA EPSON 003 YELLOW', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (36, '1010304004000120', 'CARTIDGE COMPATIBLE CF 298A', 'CARTRIDGE TONER COMPT-CF298A', 'TINTA/TONER PRINTER', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (37, '1010304004000124', 'Tinta Epson L1455 Yellow', 'TINTA EPSON 664 YELLOW', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (38, '1010304004000125', 'Tinta Epson L1455 Cyan', 'TINTA EPSON 664 CYAN', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (39, '1010304004000126', 'Tinta Epson L1455 Magenta', 'TINTA EPSON 664 MAGENTA', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (40, '1010304004000127', 'Cartridge Compatible CE505A', 'CARTRIDGE TONER COMPT-CE505A', 'TINTA/TONER PRINTER', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (41, '1010304004000129', 'Cartridge Compatible Canon 326', 'CARTRIDGE TONER CANON 326', 'TINTA/TONER PRINTER', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (42, '1010304004000133', 'Cartridge Original Canon 731 Black', 'CARTRIDGE ORIGINAL CANON 731 BLACK', 'TINTA/TONER PRINTER', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (43, '1010304004000138', 'Cartridge Compatible Canon 731 Black', 'CARTRIDGE TONER COMPT-CANON 731 BLACK', 'TINTA/TONER PRINTER', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (44, '1010304004000144', 'CATRIDGE COMPATIBLE HP LJ M102/CF217A', 'CARTRIDGE TONER COMPT-CF217A', 'TINTA/TONER PRINTER', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (45, '1010304004000146', 'TINTA EPSON 003 L1100 SERIES BLACK', 'TINTA EPSON 003 BLACK', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (46, '1010304004000147', 'TINTA EPSON 008 CYAN', 'TINTA EPSON 008 CYAN', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (47, '1010304004000148', 'TINTA EPSON 008 BLACK', 'TINTA EPSON 008 BLACK', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (48, '1010304004000149', 'TINTA EPSON 008 MAGENTA', 'TINTA EPSON 008 MAGENTA', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (49, '1010304004000150', 'TINTA EPSON 008 YELLOW', 'TINTA EPSON 008 YELLOW', 'TINTA/TONER PRINTER', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (50, '1010304999000015', 'Keyboard M-Tech MTK-02 Wire', 'KEYBOARD M-TECH MTK-02', 'BAHAN KOMPUTER', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (51, '1010305001000001', 'Sapu Lantai Plastik', 'SAPU LANTAI', 'ALAT PEMBERSIH', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (52, '1010305001000003', 'Pel Lantai', 'PEL LANTAI', 'ALAT PEMBERSIH', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (53, '1010305002000013', 'NAGATA PEL LANTAI21', 'SIKAT LANTAI NAGATA', 'ALAT PEMBERSIH', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (54, '1010305004000009', 'TEMPAT SAMPAH', 'TEMPAT SAMPAH', 'ALAT PEMBERSIH', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (55, '1010305008000003', 'PEMBERSIH KACA', 'PEMBERSIH KACA INDOMARET', 'BAHAN PEMBERSIH', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (56, '1010305008000005', 'SABUN CUCI PIRING', 'SABUN CUCI PIRING MAMA LEMON', 'BAHAN PEMBERSIH', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (57, '1010305008000040', 'Handwash', 'HAND SOAP YURI', 'BAHAN PEMBERSIH', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (58, '1010305008000070', 'PORSTEX BOTOL 1L', 'PEMBERSIH POSELEN & KERAMIK YURI PORSTEX', 'BAHAN PEMBERSIH', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (59, '1010305008000085', 'PEMBERSIH LANTAI SUPER PELL', 'PEMBERSIH LANTAI SUPERPEL', 'BAHAN PEMBERSIH', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (60, '1010305009000015', 'Tea Set', 'TEA SET NIKURA', 'ALAT MAKAN & MINUM', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (61, '1010305009000016', 'Cangkir Lepek', 'SET CANGKIR & PIRING', 'ALAT MAKAN & MINUM', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (62, '1010305012000001', 'KAMPER', 'KAMPER TOILET INDOMARET', 'PENGHARUM RUANGAN', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (63, '1010305012000002', 'PENGHARUM RUANGAN GANTUNG', 'PENGHARUM RUANGAN GLADE AIR FRESHENER', 'PENGHARUM RUANGAN', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (64, '1010305012000004', 'Pengharum Ruangan Stella Botol 225ml', 'PENGHARUM RUANGAN STELLA BOTOL', 'PENGHARUM RUANGAN', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (65, '1010305012000005', 'PENGHARUM STELLA GANTUNG', 'PENGHARUM RUANGAN STELLA AIR FRESHENER', 'PENGHARUM RUANGAN', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (66, '1010305012000006', 'KAMPER SWALOW', 'KAMPER TOILET SWALLOW', 'PENGHARUM RUANGAN', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (67, '1010305012000021 / 1010305008000092', 'Pengharum Ruangan Dahlia21 / Dahlia pengharum ruangan', 'PENGHARUM RUANGAN DAHLIA AIR FRESHENER', 'PENGHARUM RUANGAN', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (68, '1010305012000025', 'KAMPER DAHLIA', 'KAMPER TOILET DAHLIA', 'PENGHARUM RUANGAN', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (69, '1010305012000033', 'STELLA AIO MULTIPACK 3''', 'STELLA AIO MULTIPACK', 'PENGHARUM RUANGAN', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (70, '1010305012000036', 'Pengharum Ruangan Spray', 'PENGHARUM RUANGAN GLADE REFILL', 'PENGHARUM RUANGAN', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (71, '1010305999000040', 'TISSUE NICE21', 'TISU 200S', 'PERLENGKAPAN LAINNYA', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (72, '1010305999000062', 'KANTONG/PLASTIK SAMPAH', 'KANTONG PLASTIK', 'PERLENGKAPAN LAINNYA', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (73, '1010306010000006', 'BATERAI MIC', 'BATERAI MIC ENERGIZER MAX', 'BATU BATERAI', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (74, '1010306010000009', 'BATEREI ABC AAA', 'BATERAI AAA ENERGIZER MAX', 'BATU BATERAI', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (75, '1010306010000012', 'Baterai ABC Drycell C', 'BATERAI ABC NEW SPECIAL', 'BATU BATERAI', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (76, '1010306010000014', 'ALKALINE BATEREI AAA', 'BATERAI AAA ABC ALKALINE', 'BATU BATERAI', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (77, '1010309999000008', 'Taplak Meja PVC 30x45cm', 'TAPLAK MEJA', 'ALAT PEMBERSIH', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (78, '1010309999000012', 'BUKU KERJA 2023', 'BUKU KERJA 2023', 'ATK LAINNYA', 'BUKU');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (79, '1010309999000014', 'Tissue 250S', 'TISU 250S', 'PERLENGKAPAN LAINNYA', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (80, '1010310999000001', 'kabel jaringan', 'KABEL JARINGAN', 'PERLENGKAPAN LAINNYA', 'DUS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (81, '1010399999000003', 'SPON', 'SPON POLYTEX', 'ALAT PEMBERSIH', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (82, '1010399999000131', 'Mug Keramik SP2020', 'MUG KERAMIK SP2020', 'BARANG SP2020', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (83, '1010399999000216', 'IBS AMPLOP COKLAT BESAR (1)', 'IBS AMPLOP COKLAT BESAR', 'ATK LAINNYA', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (84, '1010399999000286', 'KUESIONER ST23-L2 UTP', 'KUESIONER ST23-L2 UTP', 'BARANG ST23', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (85, '1010399999000287', 'BUKU PED ST2023-UTP 2A.1', 'BUKU PED ST2023-UTP 2A.1', 'BARANG ST23', 'BUKU');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (86, '1010399999000288', 'BUKU PED ST2023-UTP 3A.1', 'BUKU PED ST2023-UTP 3A.1', 'BARANG ST23', 'BUKU');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (87, '1010399999000289', 'KUESIONER ST2023-UPB L2', 'KUESIONER ST2023-UPB L2', 'BARANG ST23', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (88, '1010399999000290', 'KUESIONER ST2023-UTL L2', 'KUESIONER ST2023-UTL L2', 'BARANG ST23', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (89, '1010399999000295', 'PENSIL ST23', 'PENSIL ST23', 'BARANG ST23', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (90, '1010399999000296', 'Block NoteST23', 'BLOCK NOTEST23', 'BARANG ST23', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (91, '1010399999000297', 'Peruncing ST23', 'PERUNCING ST23', 'BARANG ST23', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (92, '1010399999000298', 'BallpointST23', 'BALLPOINTST23', 'BARANG ST23', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (93, '1010399999000299', 'Penghapus ST23', 'PENGHAPUS ST23', 'BARANG ST23', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (94, '1010399999000300', 'Clipboard ST23', 'CLIPBOARD ST23', 'BARANG ST23', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (95, '1010399999000301', 'Goodiebag Sablon ST23', 'GOODIEBAG SABLON ST23', 'BARANG ST23', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (96, '1010399999000302', 'ID Card ST23', 'ID CARD ST23', 'BARANG ST23', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (97, '1010399999000303', 'Tali ID Card ST23', 'TALI ID CARD ST23', 'BARANG ST23', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (98, '1010399999000304', 'Topi Petugas ST23', 'TOPI PETUGAS ST23', 'BARANG ST23', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (99, 'NULL', 'NULL', 'KALENDER DINDING 2024', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (100, 'NULL', 'NULL', 'KALENDER MEJA 2024', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (101, 'NULL', 'NULL', 'BUKU KERJA 2024', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (102, 'NULL', 'NULL', 'KUESIONER K SUSENAS', 'NULL', 'KUESIONER');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (103, 'NULL', 'NULL', 'KUESIONER KP SUSENAS', 'NULL', 'KUESIONER');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (104, 'NULL', 'NULL', 'KUESIONER SERUTI INTI', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (105, 'NULL', 'NULL', 'KUESIONER VSEN24.DSBS', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (106, 'NULL', 'NULL', 'KUESIONER VSEN24.P', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (107, 'NULL', 'NULL', 'KUESIONER VSEN24.DSRT', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (108, 'NULL', 'NULL', 'KUESIONER SP PALAWIJA UTAMA', 'NULL', 'KUESIONER');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (109, 'NULL', 'NULL', 'KUESIONER SP PALAWIJA CADANGAN', 'NULL', 'KUESIONER');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (110, 'NULL', 'NULL', 'KUESIONER SP-LAHAN UTAMA', 'NULL', 'KUESIONER');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (111, 'NULL', 'NULL', 'KUESIONER SP-LAHAN CADANGAN', 'NULL', 'KUESIONER');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (112, 'NULL', 'NULL', 'REKAP KAB/KOTA SP TANAMAN PANGAN', 'NULL', 'DOKUMEN');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (113, 'NULL', 'NULL', 'CARTRIDGE TONER COMPT-CANON 731 YELLOW', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (114, 'NULL', 'NULL', 'TRIGONAL PAPER CLIPS ZRM NO.5', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (115, 'NULL', 'NULL', 'BINDER CLIP ZRM NO.111', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (116, 'NULL', 'NULL', 'PULPEN STANDARD P5 BLACK', 'NULL', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (117, 'NULL', 'NULL', 'LEM KERTAS STICK BESAR', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (118, 'NULL', 'NULL', 'STABILO BOSS', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (119, 'NULL', 'NULL', 'BINDER CLIP ZRM NO.107', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (120, 'NULL', 'NULL', 'HAND SOAP INDOMARET', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (121, 'NULL', 'NULL', 'SIKAT WC', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (122, 'NULL', 'NULL', 'TEMPAT TISU BULAT', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (123, 'NULL', 'NULL', 'TEMPAT TISU KOTAK', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (124, 'NULL', 'NULL', 'BODY WASH', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (125, 'NULL', 'NULL', 'TISU TOILET PACK', 'NULL', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (126, 'NULL', 'NULL', 'LAMPU LED 8W', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (127, 'NULL', 'NULL', 'TINTA EPSON 664 BLACK', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (128, 'NULL', 'NULL', 'CARTRIDGE COMPATIBLE HP LASER JET 15A (C7115A)', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (129, 'NULL', 'NULL', 'CARTRIDGE TONER COMPATIBLE CE285A', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (130, 'NULL', 'NULL', 'CARTRIDGE TONER COMPATIBLE CF283A', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (131, 'NULL', 'NULL', 'CARTRIDGE TONER COMPATIBLE CB435A', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (132, 'NULL', 'NULL', 'CARTRIDGE TONER COMPATIBLE CE505X', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (133, 'NULL', 'NULL', 'CARTRIDGE TONER COMPATIBLE CE255A', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (134, 'NULL', 'NULL', 'CARTRIDGE TONER COMPATIBLE CF226A', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (135, 'NULL', 'NULL', 'CARTRIDGE TONER COMPATIBLE HP 90A', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (136, 'NULL', 'NULL', 'CARTRIDGE TONER COMPATIBLE HP 92A', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (137, 'NULL', 'NULL', 'CARTRIDGE TONER COMPATIBLE HP 103A', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (138, 'NULL', 'NULL', 'CARTRIDGE TONER COMPATIBLE HP 201A', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (139, 'NULL', 'NULL', 'TINTA BOTOL 70CC BLACK', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (140, 'NULL', 'NULL', 'TINTA BOTOL 70CC CYAN', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (141, 'NULL', 'NULL', 'TINTA BOTOL 70CC MAGENTA', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (142, 'NULL', 'NULL', 'TINTA BOTOL 70CC YELLOW', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (143, 'NULL', 'NULL', 'HEAD PRINTER T04D100', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (144, 'NULL', 'NULL', 'TONER CANON LBP 2900', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (145, 'NULL', 'NULL', 'HEAD PRINTER EPSON L1210', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (146, 'NULL', 'NULL', 'TONER CARTRIDGE FOR CANON LBP 6030', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (147, 'NULL', 'NULL', 'CARTRIDGE TONER COMPT-CANON 328', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (148, 'NULL', 'NULL', 'BATERAI ABC NEW SPECIAL (BIG)', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (149, 'NULL', 'NULL', 'TISU TOILET ROOL', 'NULL', 'ROL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (150, 'NULL', 'NULL', 'KABEL PRINTER USB', 'NULL', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (151, 'NULL', 'NULL', 'TINTA PRINTER BROTHER BLACK', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (152, 'NULL', 'NULL', 'TINTA PRINTER BROTHER CYAN', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (153, 'NULL', 'NULL', 'TINTA PRINTER BROTHER MAGENTA', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (154, 'NULL', 'NULL', 'TINTA PRINTER BROTHER YELLOW', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (155, 'NULL', 'NULL', 'KERTAS FOTO GLOSSY A4', 'NULL', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (156, 'NULL', 'NULL', 'BATERAI ABC NEW SPECIAL D', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (157, 'NULL', 'NULL', 'DISINFECTANT SPRAY', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (158, 'NULL', 'NULL', 'HAND SANITIZER', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (159, 'NULL', 'NULL', 'SABUN CUCI TANGAN', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (160, 'NULL', 'NULL', 'MASKER DISPOSABLE 3 PLY', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (161, 'NULL', 'NULL', 'DISINFECTANT WIPES', 'NULL', 'PAK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (162, 'NULL', 'NULL', 'OBAT NYAMUK SPRAY', 'NULL', 'KALENG');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (163, 'NULL', 'NULL', 'OBAT NYAMUK ELEKTRIK REFILL', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (164, 'NULL', 'NULL', 'DETERGENT BUBUK', 'NULL', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (165, 'NULL', 'NULL', 'PEWANGI PAKAIAN', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (166, 'NULL', 'NULL', 'AIR MINERAL 600 ML', 'NULL', 'DUS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (167, 'NULL', 'NULL', 'KOPI BUBUK SACHET', 'NULL', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (168, 'NULL', 'NULL', 'TEH CELUP', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (169, 'NULL', 'NULL', 'GULA PASIR', 'NULL', 'KG');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (170, 'NULL', 'NULL', 'KRIMER KOPI SACHET', 'NULL', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (171, 'NULL', 'NULL', 'PULPEN STANDARD AE7 HITAM', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (172, 'NULL', 'NULL', 'PULPEN STANDARD AE7 BIRU', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (173, 'NULL', 'NULL', 'PULPEN STANDARD BOLDLINER PRO 0.8 HITAM', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (174, 'NULL', 'NULL', 'PULPEN STANDARD BOLDLINER PRO 0.8 BIRU', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (175, 'NULL', 'NULL', 'PULPEN ZEBRA HANA 4C HITAM', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (176, 'NULL', 'NULL', 'PULPEN ZEBRA HANA 4C BIRU', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (177, 'NULL', 'NULL', 'PENSIL 2B JOYKO', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (178, 'NULL', 'NULL', 'PULPEN STANDARD AE7 ZYRCON BALL HITAM', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (179, 'NULL', 'NULL', 'PULPEN STANDARD AE7 ZYRCON BALL BIRU', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (180, 'NULL', 'NULL', 'TRIGONAL PAPER CLIPS KENKO NO.1', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (181, 'NULL', 'NULL', 'TRIGONAL PAPER CLIPS KENKO NO.5', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (182, 'NULL', 'NULL', 'BINDER CLIPS JOYKO NO.107', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (183, 'NULL', 'NULL', 'BINDER CLIPS JOYKO NO.111', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (184, 'NULL', 'NULL', 'BINDER CLIPS JOYKO NO.200', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (185, 'NULL', 'NULL', 'BINDER CLIPS JOYKO NO.260', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (186, 'NULL', 'NULL', 'PENGHAPUS PENSIL KENKO B50', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (187, 'NULL', 'NULL', 'PENGHAPUS PENSIL STAEDTLER', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (188, 'NULL', 'NULL', 'MAP BPS SP2020', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (189, 'NULL', 'NULL', 'MAP BPS SAKERNAS', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (190, 'NULL', 'NULL', 'MAP BPS SUSENAS', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (191, 'NULL', 'NULL', 'MAP TALI KERTAS', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (192, 'NULL', 'NULL', 'PENGGARIS KENKO PLASTIK 30 CM', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (193, 'NULL', 'NULL', 'PENGGARIS KENKO BESI 30 CM', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (194, 'NULL', 'NULL', 'CUTTER KENKO L500', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (195, 'NULL', 'NULL', 'CUTTER JOYKO', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (196, 'NULL', 'NULL', 'ISI CUTTER KENKO S-100', 'NULL', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (197, 'NULL', 'NULL', 'RAUTAN BESAR ZRM', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (198, 'NULL', 'NULL', 'LEM KERTAS CAIR FOX', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (199, 'NULL', 'NULL', 'LEM KERTAS STICK KECIL', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (200, 'NULL', 'NULL', 'DOUBLE TIP KENKO', 'NULL', 'ROL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (201, 'NULL', 'NULL', 'LAKBAN KECIL BENING', 'NULL', 'ROL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (202, 'NULL', 'NULL', 'LAKBAN KECIL HITAM', 'NULL', 'ROL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (203, 'NULL', 'NULL', 'LAKBAN KERTAS', 'NULL', 'ROL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (204, 'NULL', 'NULL', 'STAPLER HD-50', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (205, 'NULL', 'NULL', 'STAPLER HD-100', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (206, 'NULL', 'NULL', 'STAPLER HD-10', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (207, 'NULL', 'NULL', 'ISI STAPLES KENKO NO.10', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (208, 'NULL', 'NULL', 'ISI STAPLES JOYKO NO.3', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (209, 'NULL', 'NULL', 'ISI STAPLES ZRM NO.10', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (210, 'NULL', 'NULL', 'LEAFLET SAKERNAS', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (211, 'NULL', 'NULL', 'GUNTING KECIL ZRM', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (212, 'NULL', 'NULL', 'PAGE MARKER JOYKO', 'NULL', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (213, 'NULL', 'NULL', 'POST-IT 3M', 'NULL', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (214, 'NULL', 'NULL', 'KERTAS HVS A3', 'NULL', 'RIM');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (215, 'NULL', 'NULL', 'KERTAS HVS A5', 'NULL', 'RIM');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (216, 'NULL', 'NULL', 'CARTRIDGE TONER HP 83A', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (217, 'NULL', 'NULL', 'CARTRIDGE TONER HP 78A', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (218, 'NULL', 'NULL', 'CARTRIDGE TONER CANON 325', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (219, 'NULL', 'NULL', 'CARTRIDGE TONER CANON 337', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (220, 'NULL', 'NULL', 'TINTA EPSON 664 LIGHT MAGENTA', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (221, 'NULL', 'NULL', 'TINTA EPSON 664 LIGHT CYAN', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (222, 'NULL', 'NULL', 'TINTA EPSON 001 BLACK', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (223, 'NULL', 'NULL', 'TINTA EPSON 001 CYAN', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (224, 'NULL', 'NULL', 'TINTA EPSON 001 MAGENTA', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (225, 'NULL', 'NULL', 'TINTA EPSON 001 YELLOW', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (226, 'NULL', 'NULL', 'TINTA EPSON 003 LIGHT MAGENTA', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (227, 'NULL', 'NULL', 'TINTA EPSON 003 LIGHT CYAN', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (228, 'NULL', 'NULL', 'MOUSE WIRELESS LOGITECH', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (229, 'NULL', 'NULL', 'KEYBOARD LOGITECH', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (230, 'NULL', 'NULL', 'MOUSE PAD', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (231, 'NULL', 'NULL', 'SAPU LIDI', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (232, 'NULL', 'NULL', 'PENGKI', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (233, 'NULL', 'NULL', 'KEMOCENG MICROFIBER', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (234, 'NULL', 'NULL', 'KEMOCENG BULU AYAM', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (235, 'NULL', 'NULL', 'SERBET LAP MEJA', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (236, 'NULL', 'NULL', 'SABUN CUCI PIRING SUNLIGHT', 'NULL', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (237, 'NULL', 'NULL', 'PORSTEX YURI BIRU', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (238, 'NULL', 'NULL', 'PEMBERSIH LANTAI WIPOL', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (239, 'NULL', 'NULL', 'GELAS KACA', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (240, 'NULL', 'NULL', 'PIRING KACA', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (241, 'NULL', 'NULL', 'SENDOK MAKAN', 'NULL', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (242, 'NULL', 'NULL', 'GARPU MAKAN', 'NULL', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (243, 'NULL', 'NULL', 'TERMOL', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (244, 'NULL', 'NULL', 'TEMPAT SENDOK GARPU', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (245, 'NULL', 'NULL', 'KAMPER TOILET SWALLOW GANTUNG', 'NULL', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (246, 'NULL', 'NULL', 'PENGHARUM RUANGAN STELLA SPRAY', 'NULL', 'KALENG');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (247, 'NULL', 'NULL', 'TISU 50S', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (248, 'NULL', 'NULL', 'TISU 150S', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (249, 'NULL', 'NULL', 'PLASTIK SAMPAH BESAR', 'NULL', 'ROL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (250, 'NULL', 'NULL', 'BATERAI ABC AAA KUNING', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (251, 'NULL', 'NULL', 'BATERAI ABC AA KUNING', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (252, 'NULL', 'NULL', 'BATERAI ABC AAA ALKALINE', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (253, 'NULL', 'NULL', 'BATERAI ABC AA ALKALINE', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (254, 'NULL', 'NULL', 'BATERAI ABC C ALKALINE', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (255, 'NULL', 'NULL', 'BATERAI ABC D ALKALINE', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (256, 'NULL', 'NULL', 'BATERAI ENERGIZER MAX AA', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (257, 'NULL', 'NULL', 'BATERAI MAX AA ABC ALKALINE', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (258, 'NULL', 'NULL', 'BATERAI MAX AAA ABC ALKALINE', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (259, 'NULL', 'NULL', 'BATERAI MAX C ABC ALKALINE', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (260, 'NULL', 'NULL', 'BATERAI MAX D ABC ALKALINE', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (261, 'NULL', 'NULL', 'BATERAI AAA SONY', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (262, 'NULL', 'NULL', 'BATERAI AA SONY', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (263, 'NULL', 'NULL', 'BATERAI C SONY', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (264, 'NULL', 'NULL', 'BATERAI D SONY', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (265, 'NULL', 'NULL', 'BUKU KERJA 2022', 'NULL', 'BUKU');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (266, 'NULL', 'NULL', 'MUG KERAMIK SP2021', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (267, 'NULL', 'NULL', 'MUG KERAMIK SP2022', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (268, 'NULL', 'NULL', 'IBS AMPLOP COKLAT KECIL (1)', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (269, 'NULL', 'NULL', 'IBS AMPLOP COKLAT SEDANG (1)', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (270, 'NULL', 'NULL', 'KUESIONER SAKERNAS UTAMA L2', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (271, 'NULL', 'NULL', 'KUESIONER SAKERNAS CADANGAN L2', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (272, 'NULL', 'NULL', 'KUESIONER SAKERNAS UTAMA L4', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (273, 'NULL', 'NULL', 'KUESIONER SAKERNAS CADANGAN L4', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (274, 'NULL', 'NULL', 'KUESIONER KP SAKERNAS', 'NULL', 'KUESIONER');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (275, 'NULL', 'NULL', 'KUESIONER M SUSENAS', 'NULL', 'KUESIONER');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (276, 'NULL', 'NULL', 'KUESIONER KP SUSENAS AGUSTUS', 'NULL', 'KUESIONER');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (277, 'NULL', 'NULL', 'KUESIONER SERUTI INTI VSERUTI24.INTI', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (278, 'NULL', 'NULL', 'KUESIONER SERUTI INT VSERUTI24.PER', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (279, 'NULL', 'NULL', 'KUESIONER VSEN24.K', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (280, 'NULL', 'NULL', 'KUESIONER ST2023-UTP L4', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (281, 'NULL', 'NULL', 'KUESIONER SP-LAHAN SUSENAS', 'NULL', 'KUESIONER');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (282, 'NULL', 'NULL', 'KUESIONER SP-PALAWIJA SUSENAS', 'NULL', 'KUESIONER');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (283, 'NULL', 'NULL', 'REKAP KAB/KOTA SP KOMODITAS HOLTIKULTURA', 'NULL', 'DOKUMEN');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (284, 'NULL', 'NULL', 'REKAP KAB/KOTA SP TANAMAN BUAH', 'NULL', 'DOKUMEN');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (285, 'NULL', 'NULL', 'Kuesioner Susenas September 2025 VSEN25.M (Pelatihan)', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (286, 'NULL', 'NULL', 'Kuesioner Susenas September 2025 VSEN25.KP (Pelatihan)', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (287, 'NULL', 'NULL', 'Kuesioner Seruti Inti VSERUTI25.INTI (Pelatihan)', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (288, 'NULL', 'NULL', 'Kuesioner Susenas September 2025 VSEN25.M (Pelaksanaan)', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (289, 'NULL', 'NULL', 'Kuesioner Susenas September 2025 VSEN25.KP (Pelaksanaan)', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (290, 'NULL', 'NULL', 'Kuesioner Seruti Inti VSERUTI25.INTI (Pelaksanaan)', 'NULL', 'SET');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (291, 'NULL', 'NULL', 'DOCUMENT TRAY', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (292, 'NULL', 'NULL', 'INDEX & MARKS 7 COLOR', 'NULL', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (293, 'NULL', 'NULL', 'TINTA ISI ULANG STAMPEL 5CC', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (294, 'NULL', 'NULL', 'SABUN CUCI/DETERGENT', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (295, 'NULL', 'NULL', 'CARTRIDGE COMPATIBLE 6230', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (296, 'NULL', 'NULL', 'STAPLE REMOVER', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (297, 'NULL', 'NULL', 'LEM KERTAS CAIR', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (298, 'NULL', 'NULL', 'PAPER CLIP NO. 5 50 PCS', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (299, 'NULL', 'NULL', 'PAPER CLIP NO.1 100 PCS (SILVER)', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (300, 'NULL', 'NULL', 'BINDER CLIPS ZRM NO.200', 'NULL', 'BOX');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (301, 'NULL', 'NULL', 'STABILO PACK', 'NULL', 'PACK');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (302, 'NULL', 'NULL', '3M POST-IT STICKY NOTES', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (303, 'NULL', 'NULL', 'SPIDOL BESAR HITAM', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (304, 'NULL', 'NULL', 'Pronto Mark N Notes', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (305, 'NULL', 'NULL', 'EARPHONE', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (306, 'NULL', 'NULL', 'MOUSE WIRELESS', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (307, 'NULL', 'NULL', 'MOUSE', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (308, 'NULL', 'NULL', 'MOUSEPAD', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (309, 'NULL', 'NULL', 'KEYBOARD LOGITECH', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (310, 'NULL', 'NULL', 'PENGKI', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (311, 'NULL', 'NULL', 'KEMOCENG MICROFIBER', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (312, 'NULL', 'NULL', 'SAPU LANTAI NAGA', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (313, 'NULL', 'NULL', 'PEL LANTAI ULTIMA', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (314, 'NULL', 'NULL', 'SIKAT LANTAI NAGA', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (315, 'NULL', 'NULL', 'TEMPAT SAMPAH PLASTIK', 'NULL', 'BUAH');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (316, 'NULL', 'NULL', 'PEMBERSIH KACA CLING', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (317, 'NULL', 'NULL', 'HAND SOAP LIFESBUOY', 'NULL', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (318, 'NULL', 'NULL', 'PEMBERSIH POSELEN & KERAMIK PORSTEX MERAH', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (319, 'NULL', 'NULL', 'PEMBERSIH LANTAI WANGI', 'NULL', 'BOTOL');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (320, 'NULL', 'NULL', 'PENGHARUM RUANGAN KANTOR', 'NULL', 'PCS');
INSERT INTO barang_atk (id_barang, kode_barang, nama_barang_sakti, nama_barang, kategori, satuan) VALUES (321, 'NULL', 'NULL', 'TISU WAJAH 250S', 'NULL', 'BUAH');

------------------------------------------------------
-- INSERT statements for stock (320 entries)
------------------------------------------------------
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (1, 5);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (2, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (3, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (4, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (5, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (6, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (7, 9);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (8, 9);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (9, 5);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (10, 5);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (11, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (12, -6);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (13, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (14, 7);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (15, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (16, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (17, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (18, 16);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (19, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (20, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (21, 6);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (22, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (23, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (24, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (25, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (26, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (27, -15);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (28, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (29, 44);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (30, 8);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (31, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (32, 7);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (33, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (34, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (35, 4);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (36, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (37, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (38, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (39, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (40, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (41, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (42, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (43, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (44, 7);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (45, -15);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (46, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (47, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (48, -2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (49, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (50, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (51, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (52, -2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (53, -1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (54, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (55, -1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (56, -2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (57, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (58, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (59, 5);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (60, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (61, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (62, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (63, 16);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (64, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (65, 6);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (66, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (67, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (68, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (69, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (70, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (71, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (72, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (73, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (74, 7);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (75, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (76, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (77, 4);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (78, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (79, 5);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (80, 5);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (81, 5);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (82, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (83, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (84, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (85, 7);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (86, 20);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (87, -2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (88, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (89, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (90, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (91, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (92, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (93, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (94, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (95, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (96, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (97, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (98, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (99, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (100, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (101, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (102, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (103, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (104, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (105, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (106, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (107, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (108, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (109, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (110, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (111, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (112, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (113, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (114, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (115, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (116, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (117, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (118, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (119, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (120, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (121, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (122, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (123, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (124, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (125, 8);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (126, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (127, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (128, 18);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (129, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (130, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (131, 4);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (132, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (133, 14);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (134, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (135, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (136, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (137, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (138, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (139, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (140, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (141, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (142, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (143, 4);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (144, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (145, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (146, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (147, -1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (148, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (149, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (150, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (151, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (152, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (153, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (154, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (155, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (156, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (157, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (158, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (159, -1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (160, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (161, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (162, 10);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (163, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (164, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (165, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (166, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (167, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (168, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (169, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (170, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (171, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (172, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (173, -2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (174, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (175, -1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (176, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (177, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (178, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (179, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (180, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (181, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (182, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (183, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (184, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (185, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (186, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (187, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (188, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (189, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (190, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (191, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (192, 4);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (193, 6);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (194, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (195, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (196, 12);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (197, 4);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (198, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (199, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (200, 6);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (201, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (202, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (203, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (204, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (205, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (206, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (207, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (208, 5);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (209, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (210, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (211, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (212, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (213, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (214, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (215, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (216, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (217, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (218, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (219, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (220, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (221, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (222, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (223, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (224, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (225, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (226, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (227, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (228, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (229, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (230, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (231, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (232, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (233, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (234, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (235, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (236, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (237, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (238, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (239, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (240, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (241, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (242, 14);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (243, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (244, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (245, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (246, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (247, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (248, 340);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (249, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (250, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (251, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (252, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (253, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (254, 4);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (255, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (256, 31);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (257, 19);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (258, 67);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (259, 4);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (260, 19);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (261, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (262, 3);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (263, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (264, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (265, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (266, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (267, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (268, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (269, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (270, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (271, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (272, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (273, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (274, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (275, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (276, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (277, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (278, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (279, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (280, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (281, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (282, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (283, 7);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (284, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (285, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (286, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (287, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (288, 12);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (289, 8);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (290, 15);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (291, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (292, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (293, 30);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (294, 9);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (295, 10);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (296, 37);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (297, 30);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (298, 8);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (299, 34);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (300, 10);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (301, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (302, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (303, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (304, 4);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (305, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (306, 2);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (307, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (308, 1);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (309, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (310, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (311, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (312, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (313, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (314, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (315, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (316, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (317, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (318, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (319, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (320, 0);
INSERT INTO stock (id_barang, jumlah_tersedia) VALUES (321, 0);